"use client";

import { useState, useTransition } from "react";
import { Sparkles, Gauge, Target, Users, MessagesSquare, Lightbulb, AlertTriangle, ListChecks } from "lucide-react";
import { runResearchAction } from "@/app/dashboard/projects/[id]/research-actions";
import { Button } from "@/components/ui/Button";
import { Alert } from "@/components/ui/Alert";
import { Badge } from "@/components/ui/Badge";
import { Spinner } from "@/components/ui/Spinner";
import { playChime } from "@/lib/sound";
import type { ResearchResult, Competitor } from "@/lib/ai/research-schema";

const CATEGORY_TONE: Record<Competitor["category"], "accent" | "warning" | "neutral"> = {
  direct: "warning",
  indirect: "neutral",
  substitute: "accent",
};

function List({ icon: Icon, title, items }: { icon: typeof Users; title: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <div>
      <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-neutral-300">
        <Icon className="h-4 w-4" aria-hidden />
        {title}
      </div>
      <ul className="space-y-2">
        {items.map((item) => (
          <li key={item} className="rounded-xl bg-neutral-900/60 px-3 py-2 text-sm text-neutral-300">
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

function ResearchResultView({ result }: { result: ResearchResult }) {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3">
        <div className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-4">
          <div className="mb-2 flex items-center gap-2 text-neutral-400">
            <Gauge className="h-4 w-4" aria-hidden />
            <span className="text-sm">Opportunity</span>
          </div>
          <p className="text-2xl font-black">{result.opportunityScore}/100</p>
        </div>
        <div className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-4">
          <div className="mb-2 flex items-center gap-2 text-neutral-400">
            <Target className="h-4 w-4" aria-hidden />
            <span className="text-sm">Confidence</span>
          </div>
          <p className="text-2xl font-black">{result.confidence}%</p>
        </div>
      </div>

      <p className="text-sm leading-6 text-neutral-300">{result.summary}</p>

      {result.competitors.length > 0 && (
        <div>
          <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-neutral-300">
            <Users className="h-4 w-4" aria-hidden />
            Competitors
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            {result.competitors.map((c) => (
              <div key={c.name} className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-4">
                <div className="flex items-center justify-between gap-2">
                  <p className="font-bold text-white">{c.name}</p>
                  <Badge tone={CATEGORY_TONE[c.category]}>{c.category}</Badge>
                </div>
                <p className="mt-2 text-sm text-neutral-400">{c.positioning}</p>
                <p className="mt-1 text-xs text-neutral-500">Pricing: {c.pricingSignal}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="grid gap-6 md:grid-cols-2">
        <List icon={Target} title="Demand signals" items={result.demandSignals} />
        <List icon={MessagesSquare} title="Incumbent complaints" items={result.reviewComplaints} />
        <List icon={Lightbulb} title="Differentiators" items={result.differentiators} />
        <List icon={AlertTriangle} title="Risks" items={result.risks} />
      </div>

      <List icon={ListChecks} title="Recommended next actions" items={result.nextActions} />
    </div>
  );
}

export function ResearchPanel({
  projectId,
  latest,
  configured,
}: {
  projectId: string;
  latest: ResearchResult | null;
  configured: boolean;
}) {
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function run() {
    setError(null);
    startTransition(async () => {
      const res = await runResearchAction(projectId);
      if (res.error) setError(res.error);
      else playChime();
    });
  }

  return (
    <section className="space-y-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-lg font-bold">Live AI Research</h2>
          <p className="text-sm text-neutral-400">
            Evidence-directional analysis generated by Claude — hypotheses to validate, not facts.
          </p>
        </div>
        <Button onClick={run} loading={pending} disabled={!configured}>
          <Sparkles className="h-4 w-4" aria-hidden />
          {latest ? "Re-run analysis" : "Run research"}
        </Button>
      </div>

      <div className="mt-5">
        {!configured && (
          <Alert tone="info" title="AI temporarily unavailable">
            Live AI Research will be back shortly — please try again in a moment.
          </Alert>
        )}
        {error && (
          <Alert tone="error" className="mb-4">
            {error}
          </Alert>
        )}
        {pending && (
          <div className="flex items-center gap-2 py-4">
            <Spinner />
            <span className="text-sm text-neutral-400">Analyzing — this can take up to a minute…</span>
          </div>
        )}
        {!pending && latest && <ResearchResultView result={latest} />}
        {!pending && !latest && configured && !error && (
          <p className="text-sm text-neutral-500">No research run yet. Click “Run research”.</p>
        )}
      </div>
    </section>
  );
}
