import { ContentPage } from "@/components/ContentPage";

export const metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <ContentPage title="Terms of Service" updated="July 2026">
      <p>
        By creating an account or using Teckro (the &ldquo;Service&rdquo;), you agree to these
        terms. This is a plain-language summary intended as a starting template — have it reviewed
        by a lawyer before relying on it commercially.
      </p>

      <h2>Using the service</h2>
      <p>
        You may use Teckro to research and plan your own ventures. You are responsible for the
        content you enter and for how you act on the outputs.
      </p>

      <h2>Accounts</h2>
      <p>
        You must provide accurate information and keep your credentials secure. You are responsible
        for activity under your account.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Research, analyses and reports are generated by AI and are <em>directional</em> — they are
        hypotheses to validate, not professional, financial, or legal advice. You should verify
        conclusions before acting on them. Teckro is not liable for decisions made based on its
        output.
      </p>

      <h2>Payments</h2>
      <p>
        Paid plans are billed through Stripe. Subscriptions renew until cancelled; you can cancel
        anytime from Billing. Fees are non-refundable except where required by law.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Don&apos;t attempt to break, overload, or reverse-engineer the Service.</li>
        <li>Don&apos;t use it for unlawful purposes or to infringe others&apos; rights.</li>
      </ul>

      <h2>Changes</h2>
      <p>
        We may update these terms; continued use after changes constitutes acceptance. We may
        suspend accounts that violate these terms.
      </p>
    </ContentPage>
  );
}
