import type { ResearchResult } from "@/lib/ai/research-schema";
import {
  ANALYSIS_KINDS,
  ANALYSIS_CONFIG,
  type AnalysisKind,
  type AnalysisResult,
} from "@/lib/ai/analysis-kinds";

export type ReportSubsection = { heading: string; bullets: string[] };
export type ReportSection = {
  heading: string;
  body?: string;
  bullets?: string[];
  subsections?: ReportSubsection[];
};
export type FounderReport = {
  title: string;
  subtitle: string;
  sections: ReportSection[];
};

export type ReportProject = {
  name: string;
  idea: string;
  audience: string | null;
  problem: string | null;
};

/** Deterministically assemble a founder report from the AI research + analyses. */
export function buildFounderReport(
  project: ReportProject,
  research: ResearchResult | null,
  analyses: Record<AnalysisKind, AnalysisResult | null>
): FounderReport {
  const sections: ReportSection[] = [];

  sections.push({
    heading: "Overview",
    body: project.idea,
    bullets: [
      project.audience?.trim() ? `Audience: ${project.audience}` : null,
      project.problem?.trim() ? `Problem: ${project.problem}` : null,
    ].filter((x): x is string => Boolean(x)),
  });

  if (research) {
    sections.push({
      heading: "Opportunity",
      body: research.summary,
      bullets: [
        `Opportunity score: ${research.opportunityScore}/100`,
        `Confidence: ${research.confidence}%`,
      ],
    });

    if (research.competitors.length) {
      sections.push({
        heading: "Competitors",
        bullets: research.competitors.map(
          (c) => `${c.name} (${c.category}) — ${c.positioning} · Pricing: ${c.pricingSignal}`
        ),
      });
    }

    const pushList = (heading: string, items: string[]) => {
      if (items.length) sections.push({ heading, bullets: items });
    };
    pushList("Demand signals", research.demandSignals);
    pushList("Incumbent complaints", research.reviewComplaints);
    pushList("Differentiators", research.differentiators);
    pushList("Risks", research.risks);
  }

  for (const kind of ANALYSIS_KINDS) {
    const analysis = analyses[kind];
    if (!analysis) continue;
    sections.push({
      heading: ANALYSIS_CONFIG[kind].title,
      body: analysis.headline,
      subsections: analysis.sections.map((s) => ({ heading: s.title, bullets: s.items })),
    });
  }

  if (research?.nextActions.length) {
    sections.push({ heading: "Recommended next actions", bullets: research.nextActions });
  }

  return {
    title: `${project.name} — Founder Report`,
    subtitle: "Evidence-directional validation report generated by Teckro.",
    sections,
  };
}

/** Whether the report contains more than just the project overview. */
export function reportIsEnriched(report: FounderReport): boolean {
  return report.sections.length > 1;
}

/** Validate stored JSON as a FounderReport (used by saved + shared report pages). */
export function parseFounderReport(content: unknown): FounderReport | null {
  if (
    content &&
    typeof content === "object" &&
    !Array.isArray(content) &&
    "title" in content &&
    "sections" in content &&
    Array.isArray((content as { sections: unknown }).sections)
  ) {
    return content as unknown as FounderReport;
  }
  return null;
}

/** Render the report as portable Markdown for download. */
export function reportToMarkdown(report: FounderReport): string {
  const lines: string[] = [`# ${report.title}`, "", `_${report.subtitle}_`, ""];
  for (const section of report.sections) {
    lines.push(`## ${section.heading}`, "");
    if (section.body) lines.push(section.body, "");
    if (section.bullets?.length) {
      for (const bullet of section.bullets) lines.push(`- ${bullet}`);
      lines.push("");
    }
    for (const sub of section.subsections ?? []) {
      lines.push(`### ${sub.heading}`, "");
      for (const bullet of sub.bullets) lines.push(`- ${bullet}`);
      lines.push("");
    }
  }
  return `${lines.join("\n").trim()}\n`;
}

/** A filesystem-safe slug for the report filename. */
export function reportSlug(report: FounderReport): string {
  return report.title.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "report";
}
