import type { ResearchResult } from "@/lib/ai/research-schema";
import {
  ANALYSIS_KINDS,
  ANALYSIS_CONFIG,
  type AnalysisKind,
  type AnalysisResult,
} from "@/lib/ai/analysis-kinds";

export type ReportSubsection = { heading: string; bullets: string[] };

/** Drives premium rendering (icon + accent) without affecting Markdown output. */
export type SectionKind =
  | "overview"
  | "opportunity"
  | "competitors"
  | "positive"
  | "risks"
  | "analysis"
  | "actions"
  | "provenance";

export type ReportSection = {
  heading: string;
  body?: string;
  bullets?: string[];
  subsections?: ReportSubsection[];
  kind?: SectionKind;
};
export type FounderReport = {
  title: string;
  subtitle: string;
  sections: ReportSection[];
  /** Present once research has run — powers the executive summary block. */
  score?: number;
  confidence?: number;
  verdict?: string;
};

/** Deterministic verdict from an opportunity score (shared by report + panel). */
export function verdictForScore(score: number): {
  label: string;
  tone: "accent" | "warning" | "danger";
} {
  if (score >= 70) return { label: "Promising — worth pursuing", tone: "accent" };
  if (score >= 50) return { label: "Possible — sharpen the wedge", tone: "warning" };
  return { label: "High risk — rethink the angle", tone: "danger" };
}

export type ReportProject = {
  name: string;
  idea: string;
  audience: string | null;
  problem: string | null;
};

/** Deterministically assemble a founder report from the AI research + analyses. */
export function buildFounderReport(
  project: ReportProject,
  research: ResearchResult | null,
  analyses: Record<AnalysisKind, AnalysisResult | null>
): FounderReport {
  const sections: ReportSection[] = [];

  sections.push({
    heading: "Overview",
    kind: "overview",
    body: project.idea,
    bullets: [
      project.audience?.trim() ? `Audience: ${project.audience}` : null,
      project.problem?.trim() ? `Problem: ${project.problem}` : null,
    ].filter((x): x is string => Boolean(x)),
  });

  if (research) {
    sections.push({
      heading: "Opportunity",
      kind: "opportunity",
      body: research.summary,
      bullets: [
        `Opportunity score: ${research.opportunityScore}/100`,
        `Confidence: ${research.confidence}%`,
      ],
    });

    if (research.competitors.length) {
      sections.push({
        heading: "Competitors",
        kind: "competitors",
        bullets: research.competitors.map(
          (c) => `${c.name} (${c.category}) — ${c.positioning} · Pricing: ${c.pricingSignal}`
        ),
      });
    }

    const pushList = (heading: string, items: string[], kind: SectionKind) => {
      if (items.length) sections.push({ heading, bullets: items, kind });
    };
    pushList("Demand signals", research.demandSignals, "positive");
    pushList("Incumbent complaints", research.reviewComplaints, "risks");
    pushList("Differentiators", research.differentiators, "positive");
    pushList("Risks", research.risks, "risks");
  }

  for (const kind of ANALYSIS_KINDS) {
    const analysis = analyses[kind];
    if (!analysis) continue;
    sections.push({
      heading: ANALYSIS_CONFIG[kind].title,
      kind: "analysis",
      body: analysis.headline,
      subsections: analysis.sections.map((s) => ({ heading: s.title, bullets: s.items })),
    });
  }

  if (research?.nextActions.length) {
    sections.push({
      heading: "Recommended next actions",
      kind: "actions",
      bullets: research.nextActions,
    });
  }

  // Provenance is always stated so readers know inference from sourced data.
  sections.push({
    heading: "Methodology & provenance",
    kind: "provenance",
    bullets: [
      "Research, SWOT, Strategy, MVP, Pricing and Landing sections are AI inference — directional hypotheses to validate, not verified facts.",
      "The Web Signals section is generated from a live web search; its Sources list contains the URLs used.",
      "Validate conclusions with real customers before making major commitments.",
    ],
  });

  return {
    title: `${project.name} — Founder Report`,
    subtitle: "AI validation report generated by Teckro.",
    sections,
    score: research?.opportunityScore,
    confidence: research?.confidence,
    verdict: research ? verdictForScore(research.opportunityScore).label : undefined,
  };
}

/** Whether the report contains more than the overview + methodology boilerplate. */
export function reportIsEnriched(report: FounderReport): boolean {
  return report.sections.length > 2;
}

/** Validate stored JSON as a FounderReport (used by saved + shared report pages). */
export function parseFounderReport(content: unknown): FounderReport | null {
  if (
    content &&
    typeof content === "object" &&
    !Array.isArray(content) &&
    "title" in content &&
    "sections" in content &&
    Array.isArray((content as { sections: unknown }).sections)
  ) {
    return content as unknown as FounderReport;
  }
  return null;
}

/** Render the report as portable Markdown for download. */
export function reportToMarkdown(report: FounderReport): string {
  const lines: string[] = [`# ${report.title}`, "", `_${report.subtitle}_`, ""];
  for (const section of report.sections) {
    lines.push(`## ${section.heading}`, "");
    if (section.body) lines.push(section.body, "");
    if (section.bullets?.length) {
      for (const bullet of section.bullets) lines.push(`- ${bullet}`);
      lines.push("");
    }
    for (const sub of section.subsections ?? []) {
      lines.push(`### ${sub.heading}`, "");
      for (const bullet of sub.bullets) lines.push(`- ${bullet}`);
      lines.push("");
    }
  }
  return `${lines.join("\n").trim()}\n`;
}

/** A filesystem-safe slug for the report filename. */
export function reportSlug(report: FounderReport): string {
  return report.title.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "report";
}
